name: publish docker image
on: push

jobs:
  publish-docker-image-registry:
    name: publish and push image to docker
    run-on: ubuntu-22.04
    eteps:
    
    - name: Checkout
      uses: actions/checkout@v4.1.1
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:  
      username:${{secrets.USERNAME}}
      password:${{secrets.}}
      
